# Generated by Django 3.0.3 on 2021-02-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0004_auto_20210209_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='updated',
        ),
    ]
