# Generated by Django 3.1.6 on 2021-02-10 18:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_remove_quiz_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(default='', max_length=30), size=2), size=4),
        ),
    ]
