# Generated by Django 3.1.6 on 2021-02-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0006_auto_20210210_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='number_of_quizzes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_problems',
            field=models.IntegerField(default=0),
        ),
    ]
