# Generated by Django 3.0.3 on 2021-02-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0008_auto_20210218_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_code',
            field=models.TextField(blank=True, default='', max_length=6, null=True, unique=True),
        ),
    ]
