# Generated by Django 3.1.6 on 2021-02-20 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0011_quiz_is_stopped'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitted_Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.TextField(default='', max_length=30, unique=True)),
                ('submitted_answer', models.TextField(default='A', max_length=1)),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teach.problem')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teach.quiz')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teach.teacher')),
            ],
        ),
    ]
