# Generated by Django 3.1.6 on 2021-02-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0013_auto_20210220_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teach.quiz'),
        ),
    ]
