# Generated by Django 3.1.6 on 2021-02-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0014_student_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.TextField(blank=True, default=None, max_length=6, null=True, unique=True),
        ),
    ]
