# Generated by Django 3.0.3 on 2021-01-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0017_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_name',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
