# Generated by Django 3.0.3 on 2021-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0018_auto_20210120_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject_class',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
    ]
