# Generated by Django 3.0.3 on 2021-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0019_auto_20210122_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.TextField(default='', max_length=30),
        ),
    ]
